name = "ClusterAnalysis"
uuid = "10587292-549a-4141-aed9-b9dca56acf27"
authors = ["AugustoCL <augustoleal72@gmail.com>", "Elias Carvalho <eliascarvdev@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
